### ISSUE TITLE
K2410 not working with current master branch

### ISSUE THREAD

**Issue by agisen** [sdungs/E4control#15]
It sends errors.

**Comment by sdungs** [comment]
What kind of error does it send? 
What kind of communication are you using? The usual serial to ethernet adapter?
Have you updated python in the meantime?

**Comment by agisen** [comment]
The root of the problem is the UTF8-encoding. I assume its needed for the 2-channel TTI?

**Comment by sdungs** [comment]
No it was not for the 2-channel TTI. I had the issue using a K2410 with a serial-to-usb adapter. I thought it's because of a new pyserial version.
I'll investigate it more...

**Comment by agisen** [comment]
Ah ok. So for us its the usual GPIB-to-ethernet, seems both adapters handle it different then...

**Comment by agisen** [comment]
If you use a serial-to-usb adapter, maybe it is a solution to add
```
if self.connection_type == 'usb':
    cmd = cmd.encode()
```
Something similar is already implemented for device.read()

**Comment by sdungs** [comment]
Added encode for usb to the write function.
