### ISSUE TITLE
Keithley 220

### ISSUE THREAD

**Issue by 32nguyen** [sdungs/E4control#17]
Hi sdungs, 
It is impressive about your work and I think this is the only hope for what I am doing. I am trying to set a current for Keithley 220 through prologix GPIB-USB. The Keithley 220 may have some related to Keithley 196. I almost surrender from reading the manual with having no clue to start. By reading your k196.py (keithley196), I really surprised that the commands are not the same as in the keithley196 tutorial. Or I may miss something. Such as where the string command is relevant in manual? (F3X)

`def setKind(self, sKind):
        if (sKind == 'DCV'):
            self.write('F0X')
        elif (sKind == 'ACV'):
            self.write('F1X')
        elif (sKind == 'OHM'):
            self.write('F2X')
        elif (sKind == 'OCO'):
            self.write('F7X')
        elif (sKind == 'DCI'):
            self.write('F3X')
        elif (sKind == 'ACI'):
            self.write('F4X')
        elif (sKind == 'dBV'):
            self.write('F5X')
        elif (sKind == 'dBI'):
            self.write('F6X')`
Would you give me some hints on this so I can start on the Keithley 220?
Bests,
Thanh

**Comment by 32nguyen** [comment]
Oh, I see F* is for Function F with X is execute letter. If I use prologix GPIB-USB, GPIB into K196, and USB into my PC, is the connection type 'usb' or 'prologix'?

Many thanks

**Comment by 32nguyen** [comment]
Hi sdungs, 

May I have the questions regardless to what I asked you above. 

In model Keithey 196, if we use the prologix GPIB-USB, does the GPIB addr (configured by Prologix GPIB Configurator) has to be the same as the GPIB of instrument (define be the switch on rear panel)

Do you have to force the Keithley to REMOTE mode (with command REN or REMOTE 7+'addr')and address it to listen ('++auto 0')? I did not see your implement it into your code or I may understand the REMOTE wrong.
Would you please help me out with this?

Bests,
Thanh

**Comment by sdungs** [comment]
Hi Thanh, 

What Keithley 196 tutorial do you talk about?

For the Keithley 220 you need to have a look in the manual and use the specific commands for programming, they are probably different to the one used for 196. You can find a manual for example here: https://physics.oregonstate.edu/~tatej/TateLabWiki/lib/exe/fetch.php?media=manuals:220_900_01c.pdf 

I haven't worked with the Prologix GPIB Configurator. Usually you set the GPIB addr for your device (Keithley 220) and then tell the Prologix adapter with which addr it has to talk. There is no GPIB addr for the Prologix adapter itself. 

Best,
Sascha

**Comment by 32nguyen** [comment]
Just want to say thanks. 
I may it work based on your suggestion.
