### ISSUE TITLE
rampVoltage() in power supplies

### ISSUE THREAD

**Issue by agisen** [sdungs/E4control#18]
All power supply devices (ISEG, K2410, K487) have the "rampVoltage()" function which is used to ramp the voltage in given steps. The function is mainly used by the measuring scripts to ramp down the voltage after the measurements.

In my opinion this function is not hardware (device) related and should therefore be moved to utils.py. If you agree, I'll take care of it.

**Comment by sdungs** [comment]
It should be used every time you set a voltage... 
Sure, go ahead.
